---
version: '3'

services:
  cowrie:
    image: borekon/cowrie
    restart: unless-stopped
    container_name: cowrie
    ports:
      - "22:2222"      
    volumes:
      - ./cowrie-etc:/cowrie/cowrie-git/etc
      - ./cowrie-var:/cowrie/cowrie-git/var
