---
version: '3'

services:
  cowrie:
    image: borekon/cowrie
    restart: unless-stopped
    container_name: cowrie
    ports:
      - "22:2222"      
    volumes:
      - ./cowrie-etc:/home/cowrie/cowrie/etc
      - ./cowrie-var:/home/cowrie/cowrie/var
